### ISSUE TITLE
Sift cmake problem

### ISSUE THREAD

**Issue by lamsking** [sophia-x/SIFT#1]
Hello,
i would like to use your code on SIFT (https://github.com/wuhuikai/SIFT),but i can't because some problem are found like...
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OPENCV_NON

**Comment by wuhuikai** [comment]
Do you install OPENCV in your system ?
